.TH "images Directory Reference" 3 "MECHA-12 Romi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
images Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMECHA12\-Demo\&.mp4\fP"
.br
.ti -1c
.RI "file \fBRomi_Pin_1\&.jpg\fP"
.br
.ti -1c
.RI "file \fBRomi_Pin_2\&.jpg\fP"
.br
.in -1c
