.TH "cotask.py" 3 "MECHA-12 Romi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cotask.py \- This file contains classes to run cooperatively scheduled tasks in a multitasking system\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcotask\&.Task\fP"
.br
.RI "Implements multitasking with scheduling and some performance logging\&. "
.ti -1c
.RI "class \fBcotask\&.TaskList\fP"
.br
.RI "A list of tasks used internally by the task scheduler\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcotask\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcotask\&.task_list\fP = \fBTaskList\fP()"
.br
.RI "This is \fBthe\fP main task list which is created for scheduling when \fR\fBcotask\&.py\fP\fP is imported into a program\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains classes to run cooperatively scheduled tasks in a multitasking system\&. 

Tasks are created as generators, functions which have infinite loops and call \fRyield\fP at least once in the loop\&. References to all the tasks to be run in the system are kept in a list maintained by class \fRCoTaskList\fP; the system scheduler then runs the tasks' \fRrun()\fP methods according to a chosen scheduling algorithm such as round-robin or highest-priority-first\&.

.PP
\fBAuthor\fP
.RS 4
JR Ridgely 
.RE
.PP
\fBDate\fP
.RS 4
2017-Jan-01 JRR Approximate date of creation of file 

.PP
2021-Dec-18 JRR Docstrings modified to work without DoxyPyPy 
.RE
.PP
\fBCopyright\fP
.RS 4
This program is copyright (c) 2017-2023 by JR Ridgely and released under the GNU Public License, version 3\&.0\&.
.RE
.PP
It is intended for educational use only, but its use is not limited thereto\&. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MECHA-12 Romi from the source code\&.
