.TH "cotask" 3 "MECHA-12 Romi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cotask
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTask\fP"
.br
.RI "Implements multitasking with scheduling and some performance logging\&. "
.ti -1c
.RI "class \fBTaskList\fP"
.br
.RI "A list of tasks used internally by the task scheduler\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtask_list\fP = \fBTaskList\fP()"
.br
.RI "This is \fBthe\fP main task list which is created for scheduling when \fR\fBcotask\&.py\fP\fP is imported into a program\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "cotask\&.task_list = \fBTaskList\fP()"

.PP
This is \fBthe\fP main task list which is created for scheduling when \fR\fBcotask\&.py\fP\fP is imported into a program\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MECHA-12 Romi from the source code\&.
