.TH "IMU" 3 "MECHA-12 Romi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMU
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIMU\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
IMU Driver
Edited: 2/18/2025

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for MECHA-12 Romi from the source code\&.
