.TH "Line_Sensor.Line_Sensor" 3 "MECHA-12 Romi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Line_Sensor.Line_Sensor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, CTRL, ADC1, ADC3, ADC5, ADC7, ADC9, ADC11, ADC13)"
.br
.ti -1c
.RI "\fBupdate\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBctrl\fP = Pin(CTRL, mode=Pin\&.OUT_PP)"
.br
.ti -1c
.RI "\fBadc1\fP = pyb\&.ADC(ADC1)"
.br
.ti -1c
.RI "\fBadc3\fP = pyb\&.ADC(ADC3)"
.br
.ti -1c
.RI "\fBadc5\fP = pyb\&.ADC(ADC5)"
.br
.ti -1c
.RI "\fBadc7\fP = pyb\&.ADC(ADC7)"
.br
.ti -1c
.RI "\fBadc9\fP = pyb\&.ADC(ADC9)"
.br
.ti -1c
.RI "\fBadc11\fP = pyb\&.ADC(ADC11)"
.br
.ti -1c
.RI "\fBadc13\fP = pyb\&.ADC(ADC13)"
.br
.ti -1c
.RI "\fBBlack\fP = array\&.array('f', [2671\&.0, 2315\&.0, 2299\&.0, 2348\&.0, 2247\&.0, 2126\&.0, 2278\&.0])"
.br
.ti -1c
.RI "\fBWhite\fP = array\&.array('f', [261\&.0, 233\&.0, 241\&.0, 234\&.0, 227\&.0, 235\&.0, 249\&.0])"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Line_Sensor\&.Line_Sensor\&.__init__ ( self,  CTRL,  ADC1,  ADC3,  ADC5,  ADC7,  ADC9,  ADC11,  ADC13)"

.SH "Member Function Documentation"
.PP 
.SS "Line_Sensor\&.Line_Sensor\&.update ( self)"

.SH "Member Data Documentation"
.PP 
.SS "Line_Sensor\&.Line_Sensor\&.adc1 = pyb\&.ADC(ADC1)"

.SS "Line_Sensor\&.Line_Sensor\&.adc11 = pyb\&.ADC(ADC11)"

.SS "Line_Sensor\&.Line_Sensor\&.adc13 = pyb\&.ADC(ADC13)"

.SS "Line_Sensor\&.Line_Sensor\&.adc3 = pyb\&.ADC(ADC3)"

.SS "Line_Sensor\&.Line_Sensor\&.adc5 = pyb\&.ADC(ADC5)"

.SS "Line_Sensor\&.Line_Sensor\&.adc7 = pyb\&.ADC(ADC7)"

.SS "Line_Sensor\&.Line_Sensor\&.adc9 = pyb\&.ADC(ADC9)"

.SS "Line_Sensor\&.Line_Sensor\&.Black = array\&.array('f', [2671\&.0, 2315\&.0, 2299\&.0, 2348\&.0, 2247\&.0, 2126\&.0, 2278\&.0])"

.SS "Line_Sensor\&.Line_Sensor\&.ctrl = Pin(CTRL, mode=Pin\&.OUT_PP)"

.SS "Line_Sensor\&.Line_Sensor\&.White = array\&.array('f', [261\&.0, 233\&.0, 241\&.0, 234\&.0, 227\&.0, 235\&.0, 249\&.0])"


.SH "Author"
.PP 
Generated automatically by Doxygen for MECHA-12 Romi from the source code\&.
