.TH "Line_Sensor.py" 3 "MECHA-12 Romi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Line_Sensor.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLine_Sensor\&.Line_Sensor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLine_Sensor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MECHA-12 Romi from the source code\&.
