.TH "nb_input.py" 3 "MECHA-12 Romi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nb_input.py \- This file contains a class which can be used to read input through a serial port in a non-blocking way\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnb_input\&.NB_Input\fP"
.br
.RI "This class implements a task which reads user input one character at a time and puts characters together into lines of text\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBnb_input\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains a class which can be used to read input through a serial port in a non-blocking way\&. 

This module has been tested only on an STM32 using pyb\&.USB_VCP, but it should work on other CPU types using a UART object as the source of characters\&.

.PP
\fBAuthor\fP
.RS 4
JR Ridgely 
.RE
.PP
\fBDate\fP
.RS 4
2022-Feb-13 JRR Original file 
.RE
.PP
\fBCopyright\fP
.RS 4
(c) 2022 by JR Ridgely and released under the GNU Public License, version 3\&.
.RE
.PP
It is intended for educational use only, but its use is not limited thereto\&. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MECHA-12 Romi from the source code\&.
