.TH "nb_input" 3 "MECHA-12 Romi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nb_input
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNB_Input\fP"
.br
.RI "This class implements a task which reads user input one character at a time and puts characters together into lines of text\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MECHA-12 Romi from the source code\&.
