.TH "PID" 3 "MECHA-12 Romi" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PID
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Mecha 12
edited: 3/4/2025   
PID code for the Romi

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for MECHA-12 Romi from the source code\&.
